### ISSUE TITLE
Support for both Apple Music and Spotify

### ISSUE THREAD

**Issue by Just-Insane** [thatcherclough/CoverFlow#5]
It would be nice if the app supported both Apple Music and Spotify via a switch in the UI.

**Comment by thatcherclough** [comment]
This is a great idea! With the current UI, where do you think the best placement would be?

**Comment by Just-Insane** [comment]
I would either make a new header similar to Hue/Light Settings called “Service Settings” and have it either be a list with one active service, or use a toggle. Problem with a toggle is that if the list of services grows you have to redo the UI.

**Comment by thatcherclough** [comment]
I like those ideas. I was thinking of redoing the UI all together to make it more inviting, but either way this will definitely be added in the next update!

**Comment by thatcherclough** [comment]
I have successfully implemented this feature and it will be released within the next couple of days!

**Comment by thatcherclough** [comment]
This has been added as of version 1.3.1!
