### ISSUE TITLE
Cannot find Hue Bridge

### ISSUE THREAD

**Issue by Just-Insane** [thatcherclough/CoverFlow#6]
Having trouble connecting to the Hue bridge. Even pressing the button on the bridge does not work.

iOS 14.3, latest version of app on App Store (1.2.0).

There does not appear to be a prompt asking for local network access, and it does not show up as an option in the Privacy section of Settings.

**Comment by thatcherclough** [comment]
Interesting. The local network popup is set to show up after dismissing the splash screen for the first time, and it does for me. My guess is that it is an iOS 14.3 problem, as that is a beta. I'm going to do some research and get back to you.

**Comment by thatcherclough** [comment]
It seems like the popup should appear whenever the phone attempts to connect to a device on the network. What happens when you enter the "select bridge" menu and swipe down to refresh?

**Comment by Just-Insane** [comment]
When I do that the icon just keeps spinning and eventually times out.

There is no pop up to connect to network devices.

I’ve also tried reinstalling the app.

**Comment by thatcherclough** [comment]
I have found a better solution to make the local network prompt appear and I will push it out in the next update. Have you had experience side loading apps? I would like to test it before I push an update to make sure it works.

**Comment by Just-Insane** [comment]
I have no experience with that, but I’m willing to give it a try.

**Comment by thatcherclough** [comment]
Oh I know! Ill upload the build to test flight. It's Apple's Beta testing service. It might take a day or 2 to upload, but Ill send the link when it gets uploaded!

**Comment by Just-Insane** [comment]
Sounds great, thanks!

**Comment by thatcherclough** [comment]
Could I have your email to invite you to test the build?

**Comment by Just-Insane** [comment]
Can you send me a quick message on [Keybase](https://keybase.io/just_insane)? I’d rather not leave my email in a git comment.

**Comment by Just-Insane** [comment]
Tried the TestFlight build. I was able to get the prompt to allow network access, but still cannot find the bridge.

My network is setup with IPv6 and IPv4, not sure if that could cause issues?

**Comment by thatcherclough** [comment]
That could be it. I search for the bridges using the Hue SDK so I will look into how it works and if that would create a problem. Also, I will be adding a feature to connect to a bridge manually using it's IP address, so this may work as well.

**Comment by thatcherclough** [comment]
Quick question: When you pull down to refresh to search for your bridge, how long does the pin wheel spin for (approximately)?

**Comment by Just-Insane** [comment]
About 5-6 seconds.

**Comment by thatcherclough** [comment]
Okay thanks. I just updated the test flight build to possibly fix the searching issue and add a feature to connect to the bridge manually (using the ip address). Could you test these out? Thanks! Link: https://testflight.apple.com/join/ffhtyNQo

**Comment by Just-Insane** [comment]
Yup, it works perfectly not that I manually entered the IP address. Thanks for the quick support!

**Comment by thatcherclough** [comment]
Glad I could help!
