### ISSUE TITLE
Add bridge by ip

### ISSUE THREAD

**Issue by CattleWhisper** [thatcherclough/CoverFlow#8]
As a good and secure network, my phone and IOT devices are in different networks. So the common scan usually can’t find anything.

Would be good to add and option to add the bridge by typing the IP address directly.

![FA81F8D7-D698-4B88-8B21-81CB73637FBD](https://user-images.githubusercontent.com/7462364/101114565-82d62f80-35c0-11eb-997b-53b6b5cc829d.jpeg)
An example from the iLightShow app

**Comment by thatcherclough** [comment]
That is very smart to put them on separate networks! I will definitely add this in the next update.

**Comment by CattleWhisper** [comment]
Also. When you upload to TestFlight, share the link so I can join in.

**Comment by thatcherclough** [comment]
Will do!

**Comment by thatcherclough** [comment]
I just implemented this feature in the latest test flight build. Let me know if it works for you! Test Flight link: https://testflight.apple.com/join/ffhtyNQo

**Comment by CattleWhisper** [comment]
It worked 👍
