### ISSUE TITLE
Multiple colors

### ISSUE THREAD

**Issue by CattleWhisper** [thatcherclough/CoverFlow#9]
When selected multiple lights, you could have two modes:
- All be the same color.
- Each light a different color and cycles between them.

**Comment by thatcherclough** [comment]
That's a good idea! I only have one hue light so it may be hard to implement, but I will look into it.

**Comment by thatcherclough** [comment]
I am currently implementing a "randomize color order switch" that would cause the different lights to display different colors at the same time, and it will be included in the next update.

**Comment by thatcherclough** [comment]
This has been added as of version 1.3.1!
